repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
        args: ['--maxkb=1000']
        exclude: \.ipynb

  - repo: https://github.com/python-poetry/poetry
    rev: '1.7.0'
    hooks:
      - id: poetry-check
  - repo: local
    hooks:
      - id: format
        name: format
        entry: poetry run ruff format .
        language: system
        types: [python]
      - id: lint
        name: lint
        entry: poetry run ruff check . --fix
        language: system
        types: [python]
      - id: pytest
        name: pytest
        entry: poetry run pytest tests/
        language: system
        types: [python]
